language: python
python:
  - "3.6"
env:
  global:
    # Doctr deploy key for moorepants/resume
    - secure: "MmclUesJrtBmh+LBvRsK2hDWmhFSVtZzoVmieBEgufB/cfOkFnyuR02b8xXZm0/B2PScCN42CBhfNoqEZTYUeZLUViNKSnbdQEdIPFPRR5wJLR7vU7aC8jcj+CEhLbPIGZvXWMkevcAWp09sW+hon5p3OUc0kEKVBoigHFN09Rc="
before_install:
  - sudo apt update
  - sudo apt install -y texlive texlive-latex-extra texlive-bibtex-extra biber
  - pip install doctr
script:
  - set -e
  - make
  - mkdir output
  - mv resume.pdf output/
  - if [[ -z "$TRAVIS_TAG" ]]; then
      DEPLOY_DIR=".";
    else
      DEPLOY_DIR="$TRAVIS_TAG";
    fi
  - doctr deploy --build-tags --built-docs output/ $DEPLOY_DIR
